version: '3.8'
services:
  app:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
    volumes:
      - ./logs:/app/logs
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "@123456@"
      MYSQL_DATABASE: paymentdb
    ports:
      - "3316:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p@123456@" ]
      interval: 5s
      retries: 5
volumes:
  mysql-data: